theme: minima

#include images
include: 
  - _images
  - _pages

#pages
header_pages:
  - index.md
  - about.md
  - science.md
  - tech.md

plugins:
  - jekyll-archives

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: archive
  permalinks:
    category: /category/:name/
    tag: /tag/:name/